name: Build macOS

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ''

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install cmake glm molten-vk vulkan-loader vulkan-headers glslang

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DFVD_VERSION=${{ inputs.version }}

      - name: Build
        run: cmake --build build -j 4

      - name: Package macOS
        run: |
          strip -x "build/FVD++.app/Contents/MacOS/FVD++"
          codesign --force --deep --sign - "build/FVD++.app"
          ditto -c -k --keepParent "build/FVD++.app" fvd-macos-arm64.zip

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: fvd-macos-arm64.zip
